local config = require("clide.config")

describe("config", function()
  it("returns defaults before setup", function()
    assert.equals("auto", config.get().terminal.provider)
    assert.equals(true, config.get().review.inline)
    assert.equals("off", config.get().follow)
  end)

  it("deep-merges user opts over defaults", function()
    config.setup({ follow = "both", terminal = { split_side = "left" } })
    assert.equals("both", config.get().follow)
    assert.equals("left", config.get().terminal.split_side)
    assert.equals("auto", config.get().terminal.provider)
  end)
end)
