local fs = require("clide.util.fs")

local function tmpdir()
  local path = os.tmpname()
  os.remove(path)
  vim.uv.fs_mkdir(path, 448)
  return path
end

describe("util.fs", function()
  describe("write_file / read_file", function()
    it("writes and reads string data", function()
      local dir = tmpdir()
      local path = dir .. "/test.txt"
      fs.write_file(path, "hello world", 384)
      local data = fs.read_file(path)
      assert.equals("hello world", data)
      vim.uv.fs_unlink(path)
      vim.uv.fs_rmdir(dir)
    end)

    it("read_file returns nil for missing file", function()
      local data, err = fs.read_file("/nonexistent/path.lock")
      assert.is_nil(data)
      assert.is_not_nil(err)
    end)
  end)

  describe("mkdir_p", function()
    it("creates nested directories", function()
      local root = tmpdir()
      local nested = root .. "/a/b/c"
      fs.mkdir_p(nested, 448)
      assert.equals(1, vim.fn.isdirectory(nested))
      vim.uv.fs_rmdir(nested)
      vim.uv.fs_rmdir(root .. "/a/b")
      vim.uv.fs_rmdir(root .. "/a")
      vim.uv.fs_rmdir(root)
    end)

    it("does not error on existing directory", function()
      local dir = tmpdir()
      fs.mkdir_p(dir, 448) -- exists already, should not error
      assert.equals(1, vim.fn.isdirectory(dir))
      vim.uv.fs_rmdir(dir)
    end)
  end)

  describe("list_locks", function()
    it("returns .lock files in a directory", function()
      local dir = tmpdir()
      fs.write_file(dir .. "/a.lock", "a", 384)
      fs.write_file(dir .. "/b.lock", "b", 384)
      fs.write_file(dir .. "/readme.md", "text", 384)
      local locks = fs.list_locks(dir)
      locks = vim.tbl_map(function(p)
        return vim.fn.fnamemodify(p, ":t")
      end, locks)
      table.sort(locks)
      assert.same({ "a.lock", "b.lock" }, locks)
      vim.uv.fs_unlink(dir .. "/a.lock")
      vim.uv.fs_unlink(dir .. "/b.lock")
      vim.uv.fs_unlink(dir .. "/readme.md")
      vim.uv.fs_rmdir(dir)
    end)

    it("returns empty list for missing directory", function()
      assert.same({}, fs.list_locks("/nonexistent_lock_dir"))
    end)
  end)
end)
